<?php

namespace Database\Seeders;

use App\Models\Sale;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SaleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $salesData = [
            ['date' => '2023-10-11', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Ethan', 'units_sold' => 19, 'unit_price' => 1169, 'total_sales' => 22211],
            ['date' => '2023-06-05', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Bob', 'units_sold' => 14, 'unit_price' => 1649, 'total_sales' => 23086],
            ['date' => '2023-04-22', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Charlie', 'units_sold' => 13, 'unit_price' => 1508, 'total_sales' => 19504],
            ['date' => '2023-10-23', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Diana', 'units_sold' => 8, 'unit_price' => 1781, 'total_sales' => 14248],
            ['date' => '2023-07-01', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Ethan', 'units_sold' => 5, 'unit_price' => 121, 'total_sales' => 605],
            ['date' => '2023-07-31', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Bob', 'units_sold' => 4, 'unit_price' => 549, 'total_sales' => 2196],
            ['date' => '2023-01-22', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Charlie', 'units_sold' => 12, 'unit_price' => 664, 'total_sales' => 7968],
            ['date' => '2023-01-22', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Charlie', 'units_sold' => 5, 'unit_price' => 726, 'total_sales' => 3630],
            ['date' => '2023-08-13', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Diana', 'units_sold' => 7, 'unit_price' => 1961, 'total_sales' => 13727],
            ['date' => '2023-06-08', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Diana', 'units_sold' => 14, 'unit_price' => 1708, 'total_sales' => 23912],
            ['date' => '2023-08-11', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Alice', 'units_sold' => 1, 'unit_price' => 1801, 'total_sales' => 1801],
            ['date' => '2023-11-26', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Bob', 'units_sold' => 12, 'unit_price' => 1247, 'total_sales' => 14964],
            ['date' => '2023-02-17', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Bob', 'units_sold' => 14, 'unit_price' => 564, 'total_sales' => 7896],
            ['date' => '2023-04-13', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Charlie', 'units_sold' => 11, 'unit_price' => 1677, 'total_sales' => 18447],
            ['date' => '2023-03-08', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Bob', 'units_sold' => 4, 'unit_price' => 1716, 'total_sales' => 6864],
            ['date' => '2023-07-04', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Diana', 'units_sold' => 2, 'unit_price' => 894, 'total_sales' => 1788],
            ['date' => '2023-12-04', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Bob', 'units_sold' => 11, 'unit_price' => 1731, 'total_sales' => 19041],
            ['date' => '2023-10-20', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Diana', 'units_sold' => 4, 'unit_price' => 838, 'total_sales' => 3352],
            ['date' => '2023-12-25', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Diana', 'units_sold' => 11, 'unit_price' => 956, 'total_sales' => 10516],
            ['date' => '2023-12-05', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Diana', 'units_sold' => 9, 'unit_price' => 329, 'total_sales' => 2961],
            ['date' => '2023-06-26', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Diana', 'units_sold' => 8, 'unit_price' => 1426, 'total_sales' => 11408],
            ['date' => '2023-07-31', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Bob', 'units_sold' => 2, 'unit_price' => 1566, 'total_sales' => 3132],
            ['date' => '2023-10-26', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Ethan', 'units_sold' => 9, 'unit_price' => 1481, 'total_sales' => 13329],
            ['date' => '2023-07-12', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Bob', 'units_sold' => 5, 'unit_price' => 822, 'total_sales' => 4110],
            ['date' => '2023-05-11', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Ethan', 'units_sold' => 20, 'unit_price' => 571, 'total_sales' => 11420],
            ['date' => '2023-08-22', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Diana', 'units_sold' => 10, 'unit_price' => 1800, 'total_sales' => 18000],
            ['date' => '2023-09-08', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Alice', 'units_sold' => 3, 'unit_price' => 1122, 'total_sales' => 3366],
            ['date' => '2023-03-11', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Charlie', 'units_sold' => 4, 'unit_price' => 1661, 'total_sales' => 6644],
            ['date' => '2023-03-31', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Bob', 'units_sold' => 7, 'unit_price' => 481, 'total_sales' => 3367],
            ['date' => '2023-08-08', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 8, 'unit_price' => 316, 'total_sales' => 2528],
            ['date' => '2023-06-10', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Charlie', 'units_sold' => 1, 'unit_price' => 657, 'total_sales' => 657],
            ['date' => '2023-05-21', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Bob', 'units_sold' => 14, 'unit_price' => 1998, 'total_sales' => 27972],
            ['date' => '2023-09-14', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Charlie', 'units_sold' => 16, 'unit_price' => 782, 'total_sales' => 12512],
            ['date' => '2023-03-10', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Bob', 'units_sold' => 2, 'unit_price' => 1760, 'total_sales' => 3520],
            ['date' => '2023-11-30', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Charlie', 'units_sold' => 16, 'unit_price' => 307, 'total_sales' => 4912],
            ['date' => '2023-05-17', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Bob', 'units_sold' => 12, 'unit_price' => 559, 'total_sales' => 6708],
            ['date' => '2023-02-13', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Diana', 'units_sold' => 12, 'unit_price' => 785, 'total_sales' => 9420],
            ['date' => '2023-07-12', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 13, 'unit_price' => 1762, 'total_sales' => 22906],
            ['date' => '2023-08-13', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Diana', 'units_sold' => 20, 'unit_price' => 1707, 'total_sales' => 34140],
            ['date' => '2023-09-27', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Ethan', 'units_sold' => 13, 'unit_price' => 563, 'total_sales' => 7309],
            ['date' => '2023-05-01', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Diana', 'units_sold' => 4, 'unit_price' => 101, 'total_sales' => 404],
            ['date' => '2023-09-03', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Diana', 'units_sold' => 14, 'unit_price' => 391, 'total_sales' => 5474],
            ['date' => '2023-08-25', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Charlie', 'units_sold' => 7, 'unit_price' => 201, 'total_sales' => 1407],
            ['date' => '2023-07-15', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Charlie', 'units_sold' => 4, 'unit_price' => 1827, 'total_sales' => 7308],
            ['date' => '2023-04-21', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Bob', 'units_sold' => 12, 'unit_price' => 1542, 'total_sales' => 18504],
            ['date' => '2023-12-04', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Alice', 'units_sold' => 2, 'unit_price' => 1394, 'total_sales' => 2788],
            ['date' => '2023-10-26', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Charlie', 'units_sold' => 10, 'unit_price' => 1034, 'total_sales' => 10340],
            ['date' => '2023-08-31', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Ethan', 'units_sold' => 20, 'unit_price' => 1979, 'total_sales' => 39580],
            ['date' => '2023-08-08', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Bob', 'units_sold' => 1, 'unit_price' => 760, 'total_sales' => 760],
            ['date' => '2023-03-12', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Diana', 'units_sold' => 7, 'unit_price' => 1264, 'total_sales' => 8848],
            ['date' => '2023-03-18', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Ethan', 'units_sold' => 3, 'unit_price' => 1315, 'total_sales' => 3945],
            ['date' => '2023-10-10', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Ethan', 'units_sold' => 20, 'unit_price' => 159, 'total_sales' => 3180],
            ['date' => '2023-01-08', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Ethan', 'units_sold' => 17, 'unit_price' => 612, 'total_sales' => 10404],
            ['date' => '2023-08-03', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Diana', 'units_sold' => 20, 'unit_price' => 112, 'total_sales' => 2240],
            ['date' => '2023-12-03', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Charlie', 'units_sold' => 16, 'unit_price' => 834, 'total_sales' => 13344],
            ['date' => '2023-06-26', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Diana', 'units_sold' => 16, 'unit_price' => 1348, 'total_sales' => 21568],
            ['date' => '2023-06-02', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Charlie', 'units_sold' => 13, 'unit_price' => 656, 'total_sales' => 8528],
            ['date' => '2023-05-28', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 7, 'unit_price' => 556, 'total_sales' => 3892],
            ['date' => '2023-10-26', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Diana', 'units_sold' => 4, 'unit_price' => 328, 'total_sales' => 1312],
            ['date' => '2023-03-19', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Charlie', 'units_sold' => 18, 'unit_price' => 1412, 'total_sales' => 25416],
            ['date' => '2023-12-16', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Charlie', 'units_sold' => 12, 'unit_price' => 1746, 'total_sales' => 20952],
            ['date' => '2023-03-06', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Ethan', 'units_sold' => 19, 'unit_price' => 909, 'total_sales' => 17271],
            ['date' => '2023-09-06', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Charlie', 'units_sold' => 16, 'unit_price' => 1193, 'total_sales' => 19088],
            ['date' => '2023-03-14', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 18, 'unit_price' => 1417, 'total_sales' => 25506],
            ['date' => '2023-07-15', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Alice', 'units_sold' => 11, 'unit_price' => 1606, 'total_sales' => 17666],
            ['date' => '2023-04-23', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Charlie', 'units_sold' => 13, 'unit_price' => 130, 'total_sales' => 1690],
            ['date' => '2023-06-05', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Alice', 'units_sold' => 5, 'unit_price' => 1750, 'total_sales' => 8750],
            ['date' => '2023-08-27', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 11, 'unit_price' => 1925, 'total_sales' => 21175],
            ['date' => '2023-03-25', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Ethan', 'units_sold' => 19, 'unit_price' => 986, 'total_sales' => 18734],
            ['date' => '2023-05-31', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Diana', 'units_sold' => 1, 'unit_price' => 808, 'total_sales' => 808],
            ['date' => '2023-02-26', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 17, 'unit_price' => 560, 'total_sales' => 9520],
            ['date' => '2023-10-31', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Alice', 'units_sold' => 11, 'unit_price' => 1805, 'total_sales' => 19855],
            ['date' => '2023-03-02', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Diana', 'units_sold' => 4, 'unit_price' => 1539, 'total_sales' => 6156],
            ['date' => '2023-08-03', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Diana', 'units_sold' => 6, 'unit_price' => 962, 'total_sales' => 5772],
            ['date' => '2023-10-15', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Ethan', 'units_sold' => 2, 'unit_price' => 1431, 'total_sales' => 2862],
            ['date' => '2023-06-05', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Ethan', 'units_sold' => 9, 'unit_price' => 650, 'total_sales' => 5850],
            ['date' => '2023-08-23', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Bob', 'units_sold' => 9, 'unit_price' => 1350, 'total_sales' => 12150],
            ['date' => '2023-01-30', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Diana', 'units_sold' => 19, 'unit_price' => 1490, 'total_sales' => 28310],
            ['date' => '2023-05-15', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 5, 'unit_price' => 677, 'total_sales' => 3385],
            ['date' => '2023-10-08', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Ethan', 'units_sold' => 19, 'unit_price' => 1691, 'total_sales' => 32129],
            ['date' => '2023-05-06', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 20, 'unit_price' => 1743, 'total_sales' => 34860],
            ['date' => '2023-03-05', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 7, 'unit_price' => 976, 'total_sales' => 6832],
            ['date' => '2023-06-06', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Bob', 'units_sold' => 3, 'unit_price' => 1339, 'total_sales' => 4017],
            ['date' => '2023-09-16', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Diana', 'units_sold' => 2, 'unit_price' => 972, 'total_sales' => 1944],
            ['date' => '2023-02-13', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Diana', 'units_sold' => 5, 'unit_price' => 1416, 'total_sales' => 7080],
            ['date' => '2023-05-11', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Diana', 'units_sold' => 18, 'unit_price' => 1873, 'total_sales' => 33714],
            ['date' => '2023-03-02', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Ethan', 'units_sold' => 15, 'unit_price' => 816, 'total_sales' => 12240],
            ['date' => '2023-04-07', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 16, 'unit_price' => 1710, 'total_sales' => 27360],
            ['date' => '2023-05-01', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 6, 'unit_price' => 1833, 'total_sales' => 10998],
            ['date' => '2023-06-13', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Diana', 'units_sold' => 6, 'unit_price' => 910, 'total_sales' => 5460],
            ['date' => '2023-10-08', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Diana', 'units_sold' => 3, 'unit_price' => 308, 'total_sales' => 924],
            ['date' => '2023-03-21', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 18, 'unit_price' => 1468, 'total_sales' => 26424],
            ['date' => '2023-03-19', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Bob', 'units_sold' => 6, 'unit_price' => 574, 'total_sales' => 3444],
            ['date' => '2023-03-22', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 18, 'unit_price' => 130, 'total_sales' => 2340],
            ['date' => '2023-10-15', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Diana', 'units_sold' => 3, 'unit_price' => 625, 'total_sales' => 1875],
            ['date' => '2023-02-14', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Bob', 'units_sold' => 18, 'unit_price' => 729, 'total_sales' => 13122],
            ['date' => '2023-11-15', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Bob', 'units_sold' => 3, 'unit_price' => 1100, 'total_sales' => 3300],
            ['date' => '2023-03-24', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Diana', 'units_sold' => 4, 'unit_price' => 579, 'total_sales' => 2316],
            ['date' => '2023-12-26', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Charlie', 'units_sold' => 16, 'unit_price' => 535, 'total_sales' => 8560],
            ['date' => '2023-06-01', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 19, 'unit_price' => 595, 'total_sales' => 11305],
            ['date' => '2023-10-02', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Alice', 'units_sold' => 3, 'unit_price' => 1951, 'total_sales' => 5853],
            ['date' => '2023-04-29', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Diana', 'units_sold' => 6, 'unit_price' => 466, 'total_sales' => 2796],
            ['date' => '2023-05-09', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Diana', 'units_sold' => 13, 'unit_price' => 802, 'total_sales' => 10426],
            ['date' => '2023-05-31', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Charlie', 'units_sold' => 16, 'unit_price' => 731, 'total_sales' => 11696],
            ['date' => '2023-04-10', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Bob', 'units_sold' => 1, 'unit_price' => 1773, 'total_sales' => 1773],
            ['date' => '2023-08-15', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 8, 'unit_price' => 830, 'total_sales' => 6640],
            ['date' => '2023-09-01', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Bob', 'units_sold' => 14, 'unit_price' => 226, 'total_sales' => 3164],
            ['date' => '2023-12-02', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Ethan', 'units_sold' => 9, 'unit_price' => 1459, 'total_sales' => 13131],
            ['date' => '2023-02-16', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Charlie', 'units_sold' => 18, 'unit_price' => 245, 'total_sales' => 4410],
            ['date' => '2023-03-21', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 8, 'unit_price' => 146, 'total_sales' => 1168],
            ['date' => '2023-08-10', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Diana', 'units_sold' => 17, 'unit_price' => 946, 'total_sales' => 16082],
            ['date' => '2023-06-19', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Diana', 'units_sold' => 8, 'unit_price' => 465, 'total_sales' => 3720],
            ['date' => '2023-08-24', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Charlie', 'units_sold' => 17, 'unit_price' => 594, 'total_sales' => 10098],
            ['date' => '2023-05-06', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 9, 'unit_price' => 848, 'total_sales' => 7632],
            ['date' => '2023-12-05', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Diana', 'units_sold' => 16, 'unit_price' => 980, 'total_sales' => 15680],
            ['date' => '2023-09-27', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Alice', 'units_sold' => 11, 'unit_price' => 961, 'total_sales' => 10571],
            ['date' => '2023-04-08', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 17, 'unit_price' => 1495, 'total_sales' => 25415],
            ['date' => '2023-03-19', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Alice', 'units_sold' => 15, 'unit_price' => 1917, 'total_sales' => 28755],
            ['date' => '2023-02-10', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 17, 'unit_price' => 1749, 'total_sales' => 29733],
            ['date' => '2023-02-28', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 9, 'unit_price' => 599, 'total_sales' => 5391],
            ['date' => '2023-06-08', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Diana', 'units_sold' => 4, 'unit_price' => 789, 'total_sales' => 3156],
            ['date' => '2023-09-12', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Bob', 'units_sold' => 9, 'unit_price' => 1532, 'total_sales' => 13788],
            ['date' => '2023-09-28', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Alice', 'units_sold' => 2, 'unit_price' => 1818, 'total_sales' => 3636],
            ['date' => '2023-09-01', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 15, 'unit_price' => 942, 'total_sales' => 14130],
            ['date' => '2023-05-29', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Bob', 'units_sold' => 8, 'unit_price' => 1431, 'total_sales' => 11448],
            ['date' => '2023-06-08', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Bob', 'units_sold' => 7, 'unit_price' => 1522, 'total_sales' => 10654],
            ['date' => '2023-02-03', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Bob', 'units_sold' => 7, 'unit_price' => 1120, 'total_sales' => 7840],
            ['date' => '2023-02-19', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 13, 'unit_price' => 1662, 'total_sales' => 21606],
            ['date' => '2023-11-16', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Diana', 'units_sold' => 18, 'unit_price' => 1738, 'total_sales' => 31284],
            ['date' => '2023-08-29', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Ethan', 'units_sold' => 1, 'unit_price' => 1434, 'total_sales' => 1434],
            ['date' => '2023-05-17', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 12, 'unit_price' => 1446, 'total_sales' => 17352],
            ['date' => '2023-08-05', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Charlie', 'units_sold' => 14, 'unit_price' => 1253, 'total_sales' => 17542],
            ['date' => '2023-11-21', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Bob', 'units_sold' => 20, 'unit_price' => 624, 'total_sales' => 12480],
            ['date' => '2023-06-03', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Bob', 'units_sold' => 11, 'unit_price' => 727, 'total_sales' => 7997],
            ['date' => '2023-01-24', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Diana', 'units_sold' => 8, 'unit_price' => 1871, 'total_sales' => 14968],
            ['date' => '2023-09-24', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Diana', 'units_sold' => 12, 'unit_price' => 1533, 'total_sales' => 18396],
            ['date' => '2023-06-24', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Bob', 'units_sold' => 5, 'unit_price' => 1233, 'total_sales' => 6165],
            ['date' => '2023-05-24', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Ethan', 'units_sold' => 16, 'unit_price' => 1201, 'total_sales' => 19216],
            ['date' => '2023-04-04', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Bob', 'units_sold' => 4, 'unit_price' => 185, 'total_sales' => 740],

            ['date' => '2023-01-23', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 9, 'unit_price' => 1596, 'total_sales' => 14364],
            ['date' => '2023-01-05', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Ethan', 'units_sold' => 5, 'unit_price' => 1906, 'total_sales' => 9530],
            ['date' => '2023-06-14', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Diana', 'units_sold' => 12, 'unit_price' => 834, 'total_sales' => 10008],
            ['date' => '2023-04-04', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Charlie', 'units_sold' => 7, 'unit_price' => 1812, 'total_sales' => 12684],
            ['date' => '2023-08-30', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Ethan', 'units_sold' => 3, 'unit_price' => 982, 'total_sales' => 2946],
            ['date' => '2023-07-09', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Ethan', 'units_sold' => 2, 'unit_price' => 1904, 'total_sales' => 3808],
            ['date' => '2023-01-15', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Bob', 'units_sold' => 3, 'unit_price' => 215, 'total_sales' => 645],
            ['date' => '2023-09-14', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Ethan', 'units_sold' => 7, 'unit_price' => 973, 'total_sales' => 6811],
            ['date' => '2023-02-16', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Bob', 'units_sold' => 6, 'unit_price' => 667, 'total_sales' => 4002],
            ['date' => '2023-04-02', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Alice', 'units_sold' => 11, 'unit_price' => 172, 'total_sales' => 1892],
            ['date' => '2023-07-07', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Alice', 'units_sold' => 4, 'unit_price' => 157, 'total_sales' => 628],
            ['date' => '2023-06-24', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Diana', 'units_sold' => 12, 'unit_price' => 1482, 'total_sales' => 17784],
            ['date' => '2023-02-15', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Ethan', 'units_sold' => 2, 'unit_price' => 203, 'total_sales' => 406],
            ['date' => '2023-10-29', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 14, 'unit_price' => 962, 'total_sales' => 13468],
            ['date' => '2023-11-26', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Diana', 'units_sold' => 19, 'unit_price' => 727, 'total_sales' => 13813],
            ['date' => '2023-11-26', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Diana', 'units_sold' => 7, 'unit_price' => 1398, 'total_sales' => 9796],
            ['date' => '2023-04-19', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Diana', 'units_sold' => 14, 'unit_price' => 357, 'total_sales' => 4998],
            ['date' => '2023-10-16', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 17, 'unit_price' => 1978, 'total_sales' => 33626],
            ['date' => '2023-01-23', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Bob', 'units_sold' => 12, 'unit_price' => 543, 'total_sales' => 6516],
            ['date' => '2023-08-21', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Bob', 'units_sold' => 7, 'unit_price' => 1750, 'total_sales' => 12250],
            ['date' => '2023-08-15', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Ethan', 'units_sold' => 10, 'unit_price' => 1315, 'total_sales' => 13150],
            ['date' => '2023-10-02', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Bob', 'units_sold' => 11, 'unit_price' => 1578, 'total_sales' => 17358],
            ['date' => '2023-01-02', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Bob', 'units_sold' => 5, 'unit_price' => 622, 'total_sales' => 3110],
            ['date' => '2023-08-20', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Ethan', 'units_sold' => 9, 'unit_price' => 1272, 'total_sales' => 11448],
            ['date' => '2023-03-25', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Diana', 'units_sold' => 15, 'unit_price' => 1990, 'total_sales' => 29850],
            ['date' => '2023-05-19', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Bob', 'units_sold' => 10, 'unit_price' => 1068, 'total_sales' => 10680],
            ['date' => '2023-12-27', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Ethan', 'units_sold' => 7, 'unit_price' => 1754, 'total_sales' => 12278],
            ['date' => '2023-02-28', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Alice', 'units_sold' => 19, 'unit_price' => 1472, 'total_sales' => 27968],
            ['date' => '2023-03-11', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Diana', 'units_sold' => 11, 'unit_price' => 653, 'total_sales' => 7183],
            ['date' => '2023-04-11', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Diana', 'units_sold' => 6, 'unit_price' => 739, 'total_sales' => 4434],
            ['date' => '2023-01-22', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Ethan', 'units_sold' => 20, 'unit_price' => 1427, 'total_sales' => 28540],
            ['date' => '2023-06-19', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Bob', 'units_sold' => 5, 'unit_price' => 1117, 'total_sales' => 5585],
            ['date' => '2023-07-16', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Ethan', 'units_sold' => 5, 'unit_price' => 775, 'total_sales' => 3875],
            ['date' => '2023-06-15', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'East', 'salesperson' => 'Alice', 'units_sold' => 5, 'unit_price' => 383, 'total_sales' => 1915],
            ['date' => '2023-10-03', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Charlie', 'units_sold' => 18, 'unit_price' => 525, 'total_sales' => 9450],
            ['date' => '2023-04-05', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Charlie', 'units_sold' => 16, 'unit_price' => 1880, 'total_sales' => 30080],
            ['date' => '2023-10-09', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Ethan', 'units_sold' => 13, 'unit_price' => 583, 'total_sales' => 7599],
            ['date' => '2023-09-06', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Charlie', 'units_sold' => 3, 'unit_price' => 1830, 'total_sales' => 5490],
            ['date' => '2023-10-22', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'East', 'salesperson' => 'Ethan', 'units_sold' => 20, 'unit_price' => 1973, 'total_sales' => 39460],
            ['date' => '2023-11-03', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Bob', 'units_sold' => 6, 'unit_price' => 1546, 'total_sales' => 9276],

            ['date' => '2023-01-09', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 17, 'unit_price' => 168, 'total_sales' => 2856],
            ['date' => '2023-10-22', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Diana', 'units_sold' => 15, 'unit_price' => 1447, 'total_sales' => 21705],
            ['date' => '2023-12-28', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 10, 'unit_price' => 947, 'total_sales' => 9470],
            ['date' => '2023-11-03', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'North', 'salesperson' => 'Ethan', 'units_sold' => 18, 'unit_price' => 1693, 'total_sales' => 30474],
            ['date' => '2023-12-07', 'product' => 'Smartphone', 'category' => 'Electronics', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 2, 'unit_price' => 1683, 'total_sales' => 3366],
            ['date' => '2023-10-07', 'product' => 'Smartwatch', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Diana', 'units_sold' => 16, 'unit_price' => 1906, 'total_sales' => 30496],
            ['date' => '2023-01-30', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'South', 'salesperson' => 'Diana', 'units_sold' => 5, 'unit_price' => 510, 'total_sales' => 2550],
            ['date' => '2023-05-17', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'West', 'salesperson' => 'Alice', 'units_sold' => 4, 'unit_price' => 1383, 'total_sales' => 5532],
            ['date' => '2023-10-21', 'product' => 'Tablet', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Alice', 'units_sold' => 6, 'unit_price' => 141, 'total_sales' => 846],
            ['date' => '2023-11-04', 'product' => 'Laptop', 'category' => 'Electronics', 'region' => 'North', 'salesperson' => 'Charlie', 'units_sold' => 19, 'unit_price' => 1818, 'total_sales' => 34542],
            ['date' => '2023-08-23', 'product' => 'Headphones', 'category' => 'Accessories', 'region' => 'South', 'salesperson' => 'Diana', 'units_sold' => 4, 'unit_price' => 843, 'total_sales' => 3372],
            
        ];

    }
}
